In [1]:
run hello.ipynb

Exception: File `'hello.ipynb.py'` not found.

In [2]:
run Hello.ipynb

Exception: File `'Hello.ipynb.py'` not found.

In [3]:
a = 1

In [4]:
b = 2

In [5]:
whos

Variable   Type    Data/Info
----------------------------
a          int     1
b          int     2


In [7]:
run hi.py

Exception: File `'hi.py'` not found.

In [8]:
%%writefile hi.py 
print("hi 0929!")

Writing hi.py


In [9]:
run hi.py

hi 0929!


In [10]:
a = 1

In [11]:
b = 2

In [12]:
whos 

Variable   Type    Data/Info
----------------------------
a          int     1
b          int     2


In [13]:
pip install Numpy

In [14]:
import numpy as np

In [15]:
np1 = np.array([1，2，3，4]
            )

SyntaxError: invalid character '，' (U+FF0C) (1464001952.py, line 1)

In [16]:
np1 = np.array([1，2，3，4])

SyntaxError: invalid character '，' (U+FF0C) (356052778.py, line 1)

In [17]:
np2 = np.array([5，6，7，8])

SyntaxError: invalid character '，' (U+FF0C) (2512171543.py, line 1)

In [18]:
np1 = np.array([1，2，3，4])

SyntaxError: invalid character '，' (U+FF0C) (356052778.py, line 1)

In [19]:
np1 = np.array([1，2，3，4])
np2 = np.array([5，6，7，8])


SyntaxError: invalid character '，' (U+FF0C) (4072235242.py, line 1)

In [21]:
np1 = np.array([1,2,3,4])#np.array

In [22]:
np1 = np.array([1,2,3,4])
np2 = np.array([5,6,7,8])


In [23]:
np1

array([1, 2, 3, 4])

In [24]:
np2

array([5, 6, 7, 8])

In [25]:
print(np1)
print(np2)
print(type(np1,type(np2)))

[1 2 3 4]
[5 6 7 8]


TypeError: type() takes 1 or 3 arguments

In [26]:
np3 = np.arange(0,31,2)#np.arange

In [27]:
np3 = np.arange(0,31,2)
print(np3)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [28]:
print(np1)
print(np2)
print(type(np1),type(np2))

[1 2 3 4]
[5 6 7 8]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [41]:
np4 = np.linspace(1,15,3)#np.linspace

In [30]:
print(np4)

[ 1.  8. 15.]


In [31]:
np4 = np.linspace(1,10,10)

In [32]:
print(np4)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [33]:
np5 = np.zeros((5,))#np.zeros

In [34]:
print(np5)

[0. 0. 0. 0. 0.]


In [35]:
np6 = np.ones((5))#np.ones

In [36]:
print(np6)

[1. 1. 1. 1. 1.]


In [37]:
np7 = np.ones((5,2))

In [38]:
print(np7)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [39]:
np7 = np.ones((5,3))

In [40]:
print(np7)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [42]:
listdata = [[1,2,3,4,5]]
[[6,7,8,9,10]]

[[6, 7, 8, 9, 10]]

In [43]:
listdata = [[1,2,3,4,5]],
[[6,7,8,9,10]]

[[6, 7, 8, 9, 10]]

In [44]:
listdata

([[1, 2, 3, 4, 5]],)

In [45]:
listdata = [[1,2,3,4,5],[6,7,8,9,10]]

In [46]:
listdata

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [47]:
np8 = np.array(listdata)

In [48]:
np8

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [49]:
print(np8)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [50]:
print('維度',np8.ndim)

維度 2


In [51]:
print('形狀',np8.shape)

形狀 (2, 5)


In [52]:
print('數量',np8.size)

數量 10


In [53]:
np9 = np.arange(1,21)

In [54]:
np9

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [55]:
np10 = np9.reshape(4,5)

In [56]:
np10

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [57]:
print(np10)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [58]:
np10a = np9.reshape(5,4)

In [59]:
np10a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [60]:
print(np10a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [61]:
np10 = arange(0,9)

NameError: name 'arange' is not defined

In [62]:
np10 = np.arange(0,9)

In [63]:
print(np10)

[0 1 2 3 4 5 6 7 8]


In [64]:
print(np10[0])

0


In [65]:
print(np10[8])

8


In [66]:
print(np10[1:8])

[1 2 3 4 5 6 7]


In [67]:
print(np10[1,8])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [68]:
print(np10[:])

[0 1 2 3 4 5 6 7 8]


In [69]:
print(np10[:4])

[0 1 2 3]


In [70]:
print(np10[5:])

[5 6 7 8]


In [71]:
print(np10[1:8:-1])

[]


In [72]:
print(np10[1:8:2])

[1 3 5 7]


In [73]:
print(np10[8:1:-1])

[8 7 6 5 4 3 2]


In [74]:
np11 = np.arange(1,21).reshape(5,4)

In [75]:
print(np11)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [76]:
np11[0,2]

3

In [77]:
np11[0,3]

4

In [78]:
np11[1,2]

7

In [79]:
print(np11[1:3,2])

[ 7 11]


In [80]:
print(np11[1:3,1:3])

[[ 6  7]
 [10 11]]


In [81]:
print(np11[::2,::2])

[[ 1  3]
 [ 9 11]
 [17 19]]


In [82]:
print(np11[:,2])

[ 3  7 11 15 19]


In [83]:
print(np11[1,:])

[5 6 7 8]


In [84]:
print(np11[:,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [85]:
print(np.random.rand(2,3))

[[0.02592417 0.95565736 0.78059518]
 [0.69412643 0.84523405 0.88971461]]


In [86]:
np12 = np.genfromtxt('scores.csv', delimiter=',', skip_header=1)

In [87]:
np12

array([[ 1., 87., 85., 82.],
       [ 2., 92., 87., 90.],
       [ 3., 80., 91., 87.],
       [ 4., 78., 82., 95.],
       [ 5., 88., 89., 90.],
       [ 6., 82., 87., 88.],
       [ 7., 90., 92., 82.],
       [ 8., 87., 80., 90.],
       [ 9., 95., 78., 87.],
       [10., 90., 88., 95.],
       [11., 88., 89., 75.],
       [12., 82., 91., 66.],
       [13., 90., 82., 87.],
       [14., 87., 89., 92.],
       [15., 95., 87., 80.],
       [16., 90., 92., 78.],
       [17., 82., 80., 88.],
       [18., 90., 78., 93.],
       [19., 67., 87., 95.],
       [20., 91., 82., 88.],
       [21., 82., 81., 82.],
       [22., 79., 87., 90.],
       [23., 87., 92., 87.],
       [24., 92., 82., 95.],
       [25., 80., 90., 78.],
       [26., 78., 76., 91.],
       [27., 66., 90., 82.],
       [28., 89., 77., 89.],
       [29., 87., 95., 87.],
       [30., 73., 90., 92.]])

In [88]:
np12 = np.genfromtxt('happy.csv', delimiter=',', skip_header=1)

In [89]:
np12

array([[ 4.,  4.,  4., ..., nan, nan, nan],
       [ 3.,  3.,  4., ..., nan, nan, nan],
       [ 5.,  5.,  5., ..., nan, nan, nan],
       ...,
       [ 7.,  7.,  6., ..., nan, nan, nan],
       [ 6.,  6.,  5., ..., nan, nan, nan],
       [ 5.,  5.,  4., ..., nan, nan, nan]])

In [90]:
print(np12)

[[ 4.  4.  4. ... nan nan nan]
 [ 3.  3.  4. ... nan nan nan]
 [ 5.  5.  5. ... nan nan nan]
 ...
 [ 7.  7.  6. ... nan nan nan]
 [ 6.  6.  5. ... nan nan nan]
 [ 5.  5.  4. ... nan nan nan]]


In [91]:
np13 = np.genfromtxt('happy.csv', delimiter=',', skip_header=1)

In [92]:
np13

array([[ 4.,  4.,  4., ..., nan, nan, nan],
       [ 3.,  3.,  4., ..., nan, nan, nan],
       [ 5.,  5.,  5., ..., nan, nan, nan],
       ...,
       [ 7.,  7.,  6., ..., nan, nan, nan],
       [ 6.,  6.,  5., ..., nan, nan, nan],
       [ 5.,  5.,  4., ..., nan, nan, nan]])